[package]
name = "ICPad_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
<<<<<<< HEAD
candid = "0.10.14"
ic-cdk = "0.18.5"
ic-cdk-macros = "0.18.5"
ic-cdk-timers = "0.12.2"
ic-management-canister-types = "0.3.2"
num-traits = "0.2.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
=======
candid = "0.10"
ic-cdk = "0.18.7"
ic-cdk-macros = "0.18.7"
ic-cdk-timers = "0.12.2"

ic-management-canister-types = "0.3.3"
num-traits = "0.2.19"
serde = "1.0.219"
serde_json = "1.0.143"

>>>>>>> ab3e637 (added user canister marketplace canister and a bit of ui changes)
