[package]
name = "ICPad_frontend_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.0"
ic-cdk = "0.18.0"
ic-cdk-macros = "0.18.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
